# Generated by Django 2.0.5 on 2018-05-26 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(blank=True, max_length=255, verbose_name='Track Number')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Delivery Address')),
                ('contact_phone', models.CharField(blank=True, max_length=255, verbose_name='Contact phone')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Paid'), (2, 'Send to Client')], default=0)),
                ('total', models.IntegerField(null=True, verbose_name='Total price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(related_name='in_orders', to='product.Item')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
